config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts do
    resources :comments
  end
  root to: 'pages#welcome'
  get 'api.json', to: 'pages#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  validates_length_of :body, :minimum => 10

  has_many :comments

  def published
    self.published_at
  end

  def published=(value)
    if value
      self.published_at ||= Time.now
    else
      self.published_at = nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    if params[:post_id]
      @comments = Comment.where(post_id: params[:post_id])
    else
      @comments = Comment.all
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :author, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
    if( params['admin'] )
      render
    else
      respond_to do |format|
        format.html do
          render body: 'go away, stranger'
        end
        format.json { render action: 'go_away'}
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    markdown = Redcarpet::Markdown.new(
       Redcarpet::Render::HTML,
          no_intra_emphasis: true,
          fenced_code_blocks: true,
          disable_indented_code_blocks: true,
          autolink: true,
          tables: true,
          underline: true,
          highlight: true
    )
    return markdown.render(content).html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="alert alert-info">
  <b><%= comment.author %> said:</b>
  <%=simple_format comment.body %>
  <div class="text-muted muted"><%= time_ago_in_words comment.created_at %> ago.</div>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :post_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :post_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :author, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @comment, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing comment</h1>
</div>

<%= render 'form' %>

app/views/comments/index.html.erb
<div class="page-header">
  <%= link_to new_comment_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Comment
  <% end %>
  <h1>Listing comments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Post</th>
            <th>Author</th>
            <th>Body</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @comments) do |comment| %>
            <td><%= comment.post_id %></td>
            <td><%= comment.author %></td>
            <td><%= comment.body %></td>
            <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/new.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New comment</h1>
</div>

<%= render 'form' %>

app/views/comments/show.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_comment_path(@comment), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show comment</h1>
</div>

<dl class="dl-horizontal">
  <dt>Post:</dt>
  <dd><%= @comment.post_id %></dd>

  <dt>Author:</dt>
  <dd><%= @comment.author %></dd>

  <dt>Body:</dt>
  <dd><%= @comment.body %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'defer': true %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="/posts">Posts</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pages/welcome.html.erb
<h1>Hello World</h1>

app/views/posts/_comment_form.html.erb
<%= form_for(Comment.new(post: @post), html: { class: "form-horizontal", role: "form" }) do |f| %>
  <%= f.hidden_field :post_id, class: "form-control" %>

  <div class="form-group">
    <%= f.label :author, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :published, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :published, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @post, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing post</h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="page-header">
  <%= link_to new_post_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Post
  <% end %>
  <h1>Listing posts</h1>
</div>

      <%= @posts.each do |post| %>
        <div class="panel panel-default panel-body">
          <h2><%= link_to(post.title, post) %></h2>
          <%= markdown(post.body) %>
          <p>( <%= post.comments.count %> comments )</p>
          <hr />
          <%= link_to 'Edit', edit_post_path(post) %>
          |
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>

app/views/posts/index.rss.erb
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
  <id><%= posts_url() %></id>
  <title>My Blogz</title>
  <updated><%= @posts.maximum(:updated_at) %></updated>
  <generator>me and Rails</generator>

  <% @posts.each do |post| %>
    <entry>
      <id><%= post_url(post) %></id>
      <title><%= post.title %></title>
      <updated><%= post.updated_at %></updated>

      <summary type="html">
        <%= simple_format post.body %>
      </summary>
    </entry>
  <% end %>
</feed>

app/views/posts/new.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New post</h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header">
  <%= link_to posts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_post_path(@post), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1><%= @post.title %></h1>
  <p>Written <%= time_ago_in_words(@post.created_at) %> ago.
  <% if !@post.published_at %>
    <div class="label label-warning">Unpublished</div>
  <% end %>
</div>


  <%= markdown @post.body %>

  <hr />
  <h2>Comments / Snarks / etc</h2>
  <%= render @post.comments %>
  <%= render partial: 'posts/comment_form' %>
</dl>